CREATE TABLE [Cliente]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[Referencia] int NOT NULL,
	[Apelido] NVARCHAR(100),
	[UsuarioId] UNIQUEIDENTIFIER NOT NULL UNIQUE REFERENCES Usuario(Id) ON DELETE NO ACTION,
	[LojaId] UNIQUEIDENTIFIER NOT NULL REFERENCES [Loja](Id) ON DELETE NO ACTION,
)
