CREATE TABLE [ContasAPagar]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[Valor] decimal(18, 4) NOT NULL,
	[Status] INT NOT NULL,
	[OriginalId] UNIQUEIDENTIFIER REFERENCES [ContasAPagar](Id) ON DELETE NO ACTION DEFAULT NULL,
	[NumParcela] int NOT NULL,
	[TotParcela] int NOT NULL,
	[DataVencimento] DATETIME NOT NULL,
	[DataPagamento] DATETIME DEFAULT NULL,
	[MovimentacaoId] UNIQUEIDENTIFIER NOT NULL REFERENCES [Movimentacao](Id) ON DELETE NO ACTION,
	[LojaId] UNIQUEIDENTIFIER NOT NULL REFERENCES [Loja](Id) ON DELETE CASCADE,
)
