CREATE TABLE [ContasAReceber]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[Valor] decimal(18, 4) NOT NULL,
	[Status] NVARCHAR(20) NOT NULL CHECK ([Status] IN ('PENDENTE', 'PAGO', 'CANCELADO', 'ESTORNADO','DIVIDIDO')),
	[OriginalId] UNIQUEIDENTIFIER REFERENCES [ContasAReceber](Id) ON DELETE NO ACTION DEFAULT NULL,
	[NumParcela] int NOT NULL,
	[TotParcela] int NOT NULL,
	[DataVencimento] DATETIME NOT NULL,
	[DataPagamento] DATETIME DEFAULT NULL,
	[MovimentacaoId] UNIQUEIDENTIFIER NOT NULL REFERENCES [Movimentacao](Id) ON DELETE NO ACTION,
	[LojaId] UNIQUEIDENTIFIER NOT NULL REFERENCES [Loja](Id) ON DELETE CASCADE,
)
