CREATE TABLE [MetodoPagamento]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[Nome] NVARCHAR(100) NOT NULL,
	[Taxa] decimal(18, 4) NOT NULL,
	[LojaId] UNIQUEIDENTIFIER NOT NULL REFERENCES [Loja](Id) ON DELETE NO ACTION,
)
