CREATE TABLE [Movimentacao]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[Tipo] INT NOT NULL,
	[Data] DATETIME NOT NULL DEFAULT GETDATE(),
	[LojaId] UNIQUEIDENTIFIER NOT NULL REFERENCES [Loja](Id) ON DELETE NO ACTION,
)
