CREATE TABLE [Movimentacao]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[Tipo] NVARCHAR(20) NOT NULL CHECK ([Tipo] IN ('ENTRADAESTOQUE', 'VENDA', 'DEVOLUCAOVENDA', 'DEVOLUCAO', 'DOACAO', 'EMPRESTIMO', 'DEVOLUCAOEMPRESTIMO')),
	[Data] DATETIME NOT NULL DEFAULT GETDATE(),
	[LojaId] UNIQUEIDENTIFIER NOT NULL REFERENCES [Loja](Id) ON DELETE NO ACTION,
)
