CREATE TABLE [ProdutoMovimentacao]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[ProdutoId] UNIQUEIDENTIFIER NOT NULL REFERENCES [Produto](Id) ON DELETE NO ACTION,
	[MovimentacaoId] UNIQUEIDENTIFIER NOT NULL REFERENCES [Movimentacao](Id) ON DELETE NO ACTION,
	[Valor] decimal(18, 4) NOT NULL,
	[LojaId] UNIQUEIDENTIFIER NOT NULL REFERENCES [Loja](Id) ON DELETE NO ACTION,
)
