CREATE TABLE [Produto]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[Referencia] int NOT NULL,
	[FornecedorId] UNIQUEIDENTIFIER NOT NULL REFERENCES [Cliente](Id) ON DELETE NO ACTION,
	[Preco] decimal(18, 4) NOT NULL,
	[Status] TINYINT NOT NULL,
	[CorId] UNIQUEIDENTIFIER NOT NULL REFERENCES CorProduto(Id) ON DELETE NO ACTION,
	[TamanhoId] UNIQUEIDENTIFIER NOT NULL REFERENCES TamanhoProduto(Id) ON DELETE NO ACTION,
	[MarcaId] UNIQUEIDENTIFIER NOT NULL REFERENCES MarcaProduto(Id) ON DELETE NO ACTION,
	[TipoId] UNIQUEIDENTIFIER NOT NULL REFERENCES TipoProduto(Id) ON DELETE NO ACTION,
	[Descricao] NVARCHAR(200) NULL,
	[DataEntrada] DATETIME NOT NULL DEFAULT GETDATE(),
	[LojaId] UNIQUEIDENTIFIER NOT NULL UNIQUE REFERENCES Loja(Id) ON DELETE NO ACTION,
)
