CREATE TABLE [Telefone]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[DDI] NVARCHAR(3),
    [DDD] NVARCHAR(3),
	[Numero] NVARCHAR(15) NOT NULL,
	[Whatsapp] BIT NOT NULL DEFAULT 0,
	[UsuarioId] UNIQUEIDENTIFIER NOT NULL REFERENCES [Usuario](Id) ON DELETE CASCADE,
)
